import type { Proposal } from "@/store/proposals";

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: "prop-001",
    title: "Office Renovation Lighting Package",
    company: "Lux Solutions LLC",
    client: "Nexus Corp",
    clientEmail: "procurement@nexus.com",
    status: "sent",
    createdAt: "2026-04-10",
    updatedAt: "2026-04-12",
    notes: "Includes LED retrofits for all open-plan floors.",
    customColumns: [
      { id: "cc-warranty", label: "Warranty" },
      { id: "cc-lead", label: "Lead Time" },
    ],
    items: [
      {
        id: "item-1",
        name: "LED Panel 60x60cm",
        description: "High-efficiency 40W panel, 4000K CCT",
        qty: 48,
        unit: "pcs",
        unitPrice: 38,
        imageUrl: "", deliveryTime: "2 weeks",
        attrs: { "cc-warranty": "3 years", "cc-lead": "2 weeks" },
      },
      {
        id: "item-2",
        name: "DALI Dimmer Controller",
        description: "Single-channel DALI controller",
        qty: 12,
        unit: "pcs",
        unitPrice: 65,
        imageUrl: "", deliveryTime: "1 week",
        attrs: { "cc-warranty": "2 years", "cc-lead": "1 week" },
      },
      {
        id: "item-3",
        name: "Installation & Wiring",
        description: "Labour per floor",
        qty: 4,
        unit: "floors",
        unitPrice: 450,
        imageUrl: "", deliveryTime: "On-site",
        attrs: { "cc-warranty": "—", "cc-lead": "On-site" },
      },
    ],
  },
  {
    id: "prop-002",
    title: "Custom Dining Table Set",
    company: "Craft Interiors Co.",
    client: "The Grand Bistro",
    clientEmail: "owner@grandbistro.ae",
    status: "draft",
    createdAt: "2026-04-18",
    updatedAt: "2026-04-20",
    notes: "Solid oak, seats 6. Stain colour TBC.",
    customColumns: [{ id: "cc-color", label: "Finish / Colour" }],
    items: [
      {
        id: "item-4",
        name: "Dining Table 220x90cm",
        description: "Solid oak with natural oil finish",
        qty: 5,
        unit: "pcs",
        unitPrice: 1200,
        imageUrl: "", deliveryTime: "6 weeks",
        attrs: { "cc-color": "Natural Oak" },
      },
      {
        id: "item-5",
        name: "Dining Chair",
        description: "Upholstered seat, beech legs",
        qty: 30,
        unit: "pcs",
        unitPrice: 185,
        imageUrl: "", deliveryTime: "6 weeks",
        attrs: { "cc-color": "Fabric TBC" },
      },
    ],
  },
  {
    id: "prop-003",
    title: "Warehouse Extension – Phase 1",
    company: "BuildFast Contracting",
    client: "Al Baraka Logistics",
    clientEmail: "ops@albarakalog.com",
    status: "accepted",
    createdAt: "2026-03-28",
    updatedAt: "2026-04-05",
    notes: "Steel frame structure with insulated cladding.",
    customColumns: [],
    items: [
      {
        id: "item-6",
        name: "Steel Frame Structure",
        description: "Hot-dip galvanised, 15m span",
        qty: 1,
        unit: "lot",
        unitPrice: 24000,
        imageUrl: "", deliveryTime: "12 weeks",
        attrs: {},
      },
      {
        id: "item-7",
        name: "Insulated Roof Panel",
        description: "100mm PIR, RAL 7016",
        qty: 320,
        unit: "sqm",
        unitPrice: 42,
        imageUrl: "", deliveryTime: "4 weeks",
        attrs: {},
      },
      {
        id: "item-8",
        name: "Site Preparation",
        description: "Groundwork and foundation",
        qty: 1,
        unit: "lot",
        unitPrice: 8500,
        imageUrl: "", deliveryTime: "On-site",
        attrs: {},
      },
    ],
  },
];

export const PRODUCT_CATALOG = [
  {
    category: "Lighting",
    items: [
      { name: "LED Panel 60x60cm", unit: "pcs", unitPrice: 38 },
      { name: "LED Strip 5m", unit: "rolls", unitPrice: 22 },
      { name: "Pendant Light", unit: "pcs", unitPrice: 95 },
      { name: "DALI Dimmer Controller", unit: "pcs", unitPrice: 65 },
      { name: "Emergency Exit Light", unit: "pcs", unitPrice: 48 },
      { name: "Outdoor Floodlight 200W", unit: "pcs", unitPrice: 110 },
    ],
  },
  {
    category: "Construction",
    items: [
      { name: "Steel Frame Structure", unit: "lot", unitPrice: 24000 },
      { name: "Insulated Roof Panel", unit: "sqm", unitPrice: 42 },
      { name: "Concrete Foundation", unit: "sqm", unitPrice: 85 },
      { name: "Partition Wall", unit: "sqm", unitPrice: 65 },
      { name: "Site Preparation", unit: "lot", unitPrice: 8500 },
      { name: "Electrical First Fix", unit: "lot", unitPrice: 3200 },
    ],
  },
  {
    category: "Furniture",
    items: [
      { name: "Executive Desk 180cm", unit: "pcs", unitPrice: 650 },
      { name: "Office Chair", unit: "pcs", unitPrice: 220 },
      { name: "Dining Table 220x90cm", unit: "pcs", unitPrice: 1200 },
      { name: "Dining Chair", unit: "pcs", unitPrice: 185 },
      { name: "Bookcase 200cm", unit: "pcs", unitPrice: 340 },
      { name: "Reception Counter", unit: "pcs", unitPrice: 1800 },
    ],
  },
];
